language: python

python:
    - "3.6"

env:
    global:
    # Doctr deploy key for dask/dask-tutorial
    - secure: "ZG40FBzwgbJx8dKbdtMXVS6+oWMqw1i/dkz0MhB5RWotM+buAlFzTFGaal7FeWNf/oBa4pPw9zgAeGo2tjnNxqJIN47j+8K43vikwJp7fjtEp1ru/IS+50MCWBAARSLIh2qtymEMwIpMYLZes5JU9ZPPagEOtaWFE5IDSKUKKNBTgNihuGxRaikm9ApeP2r/6gOjEEj+Qslk+o3SzX2xwteKRSkVIPPocrPnZc2IOsuP5lCrSadO0wrawVhHUlYraPNMyZEk3ChIUUW0aWyXF8OFjN1uQ0LkAgtj+O2IcshvO8ZieRUUJuHMWTWQnv9lao/mmqiOWPsG3Sf3WPuNG8oEnMjBrlMH2yYGifpgEhxkis/mebpucaQtdtptW8Btv5O+yN8MNCf2+Y3A+QHHD8yCEVGU3V/PdZbEt9ZVjCYIwQ02k/SZ9zes9NirNP2G8Ff3agQuI7LHP1nkbTzUSBvshT3XsPkRi0Q31ZnCnJJ7/NZMNTJyL1x1OIWweV60fncoJI0n3JSvzVH76wQszg+7eagE1Tudw7n0qS24Tem4hcLjLkeOdfEl8khYCgj/aI8pezzNNc5ogL3qdFvXn5JP5zs/OuxxlpqToBBurQtujxp1JI/dwgVy392avzizimHfalcrRski94qJli8jvPnSDSbL1OzAhzw+zHIv68U="


before_install:
    - sudo apt-get update
    - sudo apt-get install graphviz

install:
    # Install conda
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda config --set always_yes yes --set changeps1 no
    - conda update conda

    # Install dependencies
    - conda env create -n test -f binder/environment.yml
    - source activate test

    # Install testing dependencies
    - conda install -c conda-forge nbconvert nbformat jupyter_client ipykernel

    # Install documentation dependencies
    - pip install nbsphinx dask-sphinx-theme

script:
    - set -e
    - source activate test
    - python prep.py --small
    - sphinx-build -M html . _build -vv
    - pip install doctr
    - doctr deploy --built-docs _build/html .

notifications:
  email: false
